// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  granteeIdentity: __t.identity(),
  workspaceId: __t.option(__t.u64()),
  channelId: __t.option(__t.u64()),
  capability: __t.string(),
  ttlSeconds: __t.u64(),
  clientRequestId: __t.option(__t.string()),
};
