// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.2.0 (commit eb11e2f5c41dce6979715ad407996270d61329f6).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AcceptHandoffReducer from "./accept_handoff_reducer";
import AcceptWorkspaceInviteReducer from "./accept_workspace_invite_reducer";
import AddConversationMemberReducer from "./add_conversation_member_reducer";
import BindAgentIdentityReducer from "./bind_agent_identity_reducer";
import BootstrapOperatorAccountReducer from "./bootstrap_operator_account_reducer";
import ClaimTaskReducer from "./claim_task_reducer";
import ClearAccountDirectoryRequestReducer from "./clear_account_directory_request_reducer";
import ClearChannelDirectoryRequestReducer from "./clear_channel_directory_request_reducer";
import ClearConversationListRequestReducer from "./clear_conversation_list_request_reducer";
import ClearConversationMemberRequestReducer from "./clear_conversation_member_request_reducer";
import ClearConversationMessageRequestReducer from "./clear_conversation_message_request_reducer";
import ClearInboxDeliveryRequestReducer from "./clear_inbox_delivery_request_reducer";
import CreateAccountReducer from "./create_account_reducer";
import CreateChannelReducer from "./create_channel_reducer";
import CreateDirectConversationReducer from "./create_direct_conversation_reducer";
import CreateGroupConversationReducer from "./create_group_conversation_reducer";
import CreateHandoffReducer from "./create_handoff_reducer";
import CreateTaskReducer from "./create_task_reducer";
import CreateThreadReducer from "./create_thread_reducer";
import CreateWorkspaceReducer from "./create_workspace_reducer";
import CreateWorkspaceChannelReducer from "./create_workspace_channel_reducer";
import CreateWorkspaceInviteReducer from "./create_workspace_invite_reducer";
import EmitAgentEventReducer from "./emit_agent_event_reducer";
import GrantCapabilityReducer from "./grant_capability_reducer";
import HeartbeatReducer from "./heartbeat_reducer";
import JoinChannelReducer from "./join_channel_reducer";
import KickFromRoomReducer from "./kick_from_room_reducer";
import LeaveChannelReducer from "./leave_channel_reducer";
import LeaveConversationReducer from "./leave_conversation_reducer";
import MarkConversationReadReducer from "./mark_conversation_read_reducer";
import MarkMessagesArchiveFailedReducer from "./mark_messages_archive_failed_reducer";
import MarkMessagesArchivedReducer from "./mark_messages_archived_reducer";
import OpenDirectConversationReducer from "./open_direct_conversation_reducer";
import RegisterAgentReducer from "./register_agent_reducer";
import RepairAccessStateReducer from "./repair_access_state_reducer";
import RepairReversePaginationFieldsReducer from "./repair_reverse_pagination_fields_reducer";
import RepairScaleIndexesReducer from "./repair_scale_indexes_reducer";
import RequestAccountDirectoryReducer from "./request_account_directory_reducer";
import RequestArchiveBatchReducer from "./request_archive_batch_reducer";
import RequestChannelDirectoryReducer from "./request_channel_directory_reducer";
import RequestConversationMembersReducer from "./request_conversation_members_reducer";
import RequestConversationMessagesReducer from "./request_conversation_messages_reducer";
import RequestConversationsReducer from "./request_conversations_reducer";
import RequestInboxDeliveriesReducer from "./request_inbox_deliveries_reducer";
import ResetDeploymentPolicyReducer from "./reset_deployment_policy_reducer";
import ResetRetentionPolicyReducer from "./reset_retention_policy_reducer";
import RevokeCapabilityReducer from "./revoke_capability_reducer";
import RunRetentionCleanupNowReducer from "./run_retention_cleanup_now_reducer";
import SendConversationMessageReducer from "./send_conversation_message_reducer";
import SendDirectMessageReducer from "./send_direct_message_reducer";
import SendThreadMessageReducer from "./send_thread_message_reducer";
import SetAccountTypeReducer from "./set_account_type_reducer";
import SetDeploymentPolicyReducer from "./set_deployment_policy_reducer";
import SetProfileReducer from "./set_profile_reducer";
import SetRetentionPolicyReducer from "./set_retention_policy_reducer";
import SetRoomConfigReducer from "./set_room_config_reducer";
import SetRoomRoleReducer from "./set_room_role_reducer";
import UnwatchThreadReducer from "./unwatch_thread_reducer";
import UpdateTaskStatusReducer from "./update_task_status_reducer";
import WatchThreadReducer from "./watch_thread_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import PublicAccountDirectoryRow from "./public_account_directory_table";
import PublicChannelDirectoryRow from "./public_channel_directory_table";
import VisibleAccountRow from "./visible_account_table";
import VisibleAccountEntitlementRow from "./visible_account_entitlement_table";
import VisibleAgentDeliveryCounterRow from "./visible_agent_delivery_counter_table";
import VisibleAgentEventRow from "./visible_agent_event_table";
import VisibleAgentProfileRow from "./visible_agent_profile_table";
import VisibleAgentSessionRow from "./visible_agent_session_table";
import VisibleArchiveCandidateMessageRow from "./visible_archive_candidate_message_table";
import VisibleCapabilityGrantRow from "./visible_capability_grant_table";
import VisibleChannelRow from "./visible_channel_table";
import VisibleChannelMemberRow from "./visible_channel_member_table";
import VisibleChannelRoleRow from "./visible_channel_role_table";
import VisibleClientRequestReceiptRow from "./visible_client_request_receipt_table";
import VisibleConversationRow from "./visible_conversation_table";
import VisibleConversationMemberRow from "./visible_conversation_member_table";
import VisibleConversationMessageRow from "./visible_conversation_message_table";
import VisibleConversationReadCursorRow from "./visible_conversation_read_cursor_table";
import VisibleDeploymentPolicyRow from "./visible_deployment_policy_table";
import VisibleDirectConversationRow from "./visible_direct_conversation_table";
import VisibleHandoffRow from "./visible_handoff_table";
import VisibleInboxDeliveryRow from "./visible_inbox_delivery_table";
import VisibleMessageRow from "./visible_message_table";
import VisibleOperatorScaleSnapshotRow from "./visible_operator_scale_snapshot_table";
import VisibleRateLimitBucketRow from "./visible_rate_limit_bucket_table";
import VisibleRateLimitPressureRow from "./visible_rate_limit_pressure_table";
import VisibleRequestedAccountDirectoryRow from "./visible_requested_account_directory_table";
import VisibleRequestedChannelDirectoryRow from "./visible_requested_channel_directory_table";
import VisibleRequestedConversationRow from "./visible_requested_conversation_table";
import VisibleRequestedConversationMemberRow from "./visible_requested_conversation_member_table";
import VisibleRequestedConversationMessageRow from "./visible_requested_conversation_message_table";
import VisibleRequestedConversationSummaryRow from "./visible_requested_conversation_summary_table";
import VisibleRequestedInboxDeliveryRow from "./visible_requested_inbox_delivery_table";
import VisibleRetentionCleanupStatRow from "./visible_retention_cleanup_stat_table";
import VisibleRetentionPolicyRow from "./visible_retention_policy_table";
import VisibleRichMessageRow from "./visible_rich_message_table";
import VisibleRoomConfigRow from "./visible_room_config_table";
import VisibleRoomRemovalReceiptRow from "./visible_room_removal_receipt_table";
import VisibleScaleRepairStatRow from "./visible_scale_repair_stat_table";
import VisibleSelfAgentProfileRow from "./visible_self_agent_profile_table";
import VisibleTaskRow from "./visible_task_table";
import VisibleTaskClaimRow from "./visible_task_claim_table";
import VisibleThreadRow from "./visible_thread_table";
import VisibleThreadWatchRow from "./visible_thread_watch_table";
import VisibleUnreadConversationMessageRow from "./visible_unread_conversation_message_table";
import VisibleUserRow from "./visible_user_table";
import VisibleWatchedMessageRow from "./visible_watched_message_table";
import VisibleWorkspaceRow from "./visible_workspace_table";
import VisibleWorkspaceChannelRow from "./visible_workspace_channel_table";
import VisibleWorkspaceMemberRow from "./visible_workspace_member_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  public_account_directory: __table({
    name: 'public_account_directory',
    indexes: [
    ],
    constraints: [
    ],
  }, PublicAccountDirectoryRow),
  public_channel_directory: __table({
    name: 'public_channel_directory',
    indexes: [
    ],
    constraints: [
    ],
  }, PublicChannelDirectoryRow),
  visible_account: __table({
    name: 'visible_account',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleAccountRow),
  visible_account_entitlement: __table({
    name: 'visible_account_entitlement',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleAccountEntitlementRow),
  visible_agent_delivery_counter: __table({
    name: 'visible_agent_delivery_counter',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleAgentDeliveryCounterRow),
  visible_agent_event: __table({
    name: 'visible_agent_event',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleAgentEventRow),
  visible_agent_profile: __table({
    name: 'visible_agent_profile',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleAgentProfileRow),
  visible_agent_session: __table({
    name: 'visible_agent_session',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleAgentSessionRow),
  visible_archive_candidate_message: __table({
    name: 'visible_archive_candidate_message',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleArchiveCandidateMessageRow),
  visible_capability_grant: __table({
    name: 'visible_capability_grant',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleCapabilityGrantRow),
  visible_channel: __table({
    name: 'visible_channel',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleChannelRow),
  visible_channel_member: __table({
    name: 'visible_channel_member',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleChannelMemberRow),
  visible_channel_role: __table({
    name: 'visible_channel_role',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleChannelRoleRow),
  visible_client_request_receipt: __table({
    name: 'visible_client_request_receipt',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleClientRequestReceiptRow),
  visible_conversation: __table({
    name: 'visible_conversation',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleConversationRow),
  visible_conversation_member: __table({
    name: 'visible_conversation_member',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleConversationMemberRow),
  visible_conversation_message: __table({
    name: 'visible_conversation_message',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleConversationMessageRow),
  visible_conversation_read_cursor: __table({
    name: 'visible_conversation_read_cursor',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleConversationReadCursorRow),
  visible_deployment_policy: __table({
    name: 'visible_deployment_policy',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleDeploymentPolicyRow),
  visible_direct_conversation: __table({
    name: 'visible_direct_conversation',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleDirectConversationRow),
  visible_handoff: __table({
    name: 'visible_handoff',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleHandoffRow),
  visible_inbox_delivery: __table({
    name: 'visible_inbox_delivery',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleInboxDeliveryRow),
  visible_message: __table({
    name: 'visible_message',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleMessageRow),
  visible_operator_scale_snapshot: __table({
    name: 'visible_operator_scale_snapshot',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleOperatorScaleSnapshotRow),
  visible_rate_limit_bucket: __table({
    name: 'visible_rate_limit_bucket',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleRateLimitBucketRow),
  visible_rate_limit_pressure: __table({
    name: 'visible_rate_limit_pressure',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleRateLimitPressureRow),
  visible_requested_account_directory: __table({
    name: 'visible_requested_account_directory',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleRequestedAccountDirectoryRow),
  visible_requested_channel_directory: __table({
    name: 'visible_requested_channel_directory',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleRequestedChannelDirectoryRow),
  visible_requested_conversation: __table({
    name: 'visible_requested_conversation',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleRequestedConversationRow),
  visible_requested_conversation_member: __table({
    name: 'visible_requested_conversation_member',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleRequestedConversationMemberRow),
  visible_requested_conversation_message: __table({
    name: 'visible_requested_conversation_message',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleRequestedConversationMessageRow),
  visible_requested_conversation_summary: __table({
    name: 'visible_requested_conversation_summary',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleRequestedConversationSummaryRow),
  visible_requested_inbox_delivery: __table({
    name: 'visible_requested_inbox_delivery',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleRequestedInboxDeliveryRow),
  visible_retention_cleanup_stat: __table({
    name: 'visible_retention_cleanup_stat',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleRetentionCleanupStatRow),
  visible_retention_policy: __table({
    name: 'visible_retention_policy',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleRetentionPolicyRow),
  visible_rich_message: __table({
    name: 'visible_rich_message',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleRichMessageRow),
  visible_room_config: __table({
    name: 'visible_room_config',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleRoomConfigRow),
  visible_room_removal_receipt: __table({
    name: 'visible_room_removal_receipt',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleRoomRemovalReceiptRow),
  visible_scale_repair_stat: __table({
    name: 'visible_scale_repair_stat',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleScaleRepairStatRow),
  visible_self_agent_profile: __table({
    name: 'visible_self_agent_profile',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleSelfAgentProfileRow),
  visible_task: __table({
    name: 'visible_task',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleTaskRow),
  visible_task_claim: __table({
    name: 'visible_task_claim',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleTaskClaimRow),
  visible_thread: __table({
    name: 'visible_thread',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleThreadRow),
  visible_thread_watch: __table({
    name: 'visible_thread_watch',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleThreadWatchRow),
  visible_unread_conversation_message: __table({
    name: 'visible_unread_conversation_message',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleUnreadConversationMessageRow),
  visible_user: __table({
    name: 'visible_user',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleUserRow),
  visible_watched_message: __table({
    name: 'visible_watched_message',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleWatchedMessageRow),
  visible_workspace: __table({
    name: 'visible_workspace',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleWorkspaceRow),
  visible_workspace_channel: __table({
    name: 'visible_workspace_channel',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleWorkspaceChannelRow),
  visible_workspace_member: __table({
    name: 'visible_workspace_member',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleWorkspaceMemberRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("accept_handoff", AcceptHandoffReducer),
  __reducerSchema("accept_workspace_invite", AcceptWorkspaceInviteReducer),
  __reducerSchema("add_conversation_member", AddConversationMemberReducer),
  __reducerSchema("bind_agent_identity", BindAgentIdentityReducer),
  __reducerSchema("bootstrap_operator_account", BootstrapOperatorAccountReducer),
  __reducerSchema("claim_task", ClaimTaskReducer),
  __reducerSchema("clear_account_directory_request", ClearAccountDirectoryRequestReducer),
  __reducerSchema("clear_channel_directory_request", ClearChannelDirectoryRequestReducer),
  __reducerSchema("clear_conversation_list_request", ClearConversationListRequestReducer),
  __reducerSchema("clear_conversation_member_request", ClearConversationMemberRequestReducer),
  __reducerSchema("clear_conversation_message_request", ClearConversationMessageRequestReducer),
  __reducerSchema("clear_inbox_delivery_request", ClearInboxDeliveryRequestReducer),
  __reducerSchema("create_account", CreateAccountReducer),
  __reducerSchema("create_channel", CreateChannelReducer),
  __reducerSchema("create_direct_conversation", CreateDirectConversationReducer),
  __reducerSchema("create_group_conversation", CreateGroupConversationReducer),
  __reducerSchema("create_handoff", CreateHandoffReducer),
  __reducerSchema("create_task", CreateTaskReducer),
  __reducerSchema("create_thread", CreateThreadReducer),
  __reducerSchema("create_workspace", CreateWorkspaceReducer),
  __reducerSchema("create_workspace_channel", CreateWorkspaceChannelReducer),
  __reducerSchema("create_workspace_invite", CreateWorkspaceInviteReducer),
  __reducerSchema("emit_agent_event", EmitAgentEventReducer),
  __reducerSchema("grant_capability", GrantCapabilityReducer),
  __reducerSchema("heartbeat", HeartbeatReducer),
  __reducerSchema("join_channel", JoinChannelReducer),
  __reducerSchema("kick_from_room", KickFromRoomReducer),
  __reducerSchema("leave_channel", LeaveChannelReducer),
  __reducerSchema("leave_conversation", LeaveConversationReducer),
  __reducerSchema("mark_conversation_read", MarkConversationReadReducer),
  __reducerSchema("mark_messages_archive_failed", MarkMessagesArchiveFailedReducer),
  __reducerSchema("mark_messages_archived", MarkMessagesArchivedReducer),
  __reducerSchema("open_direct_conversation", OpenDirectConversationReducer),
  __reducerSchema("register_agent", RegisterAgentReducer),
  __reducerSchema("repair_access_state", RepairAccessStateReducer),
  __reducerSchema("repair_reverse_pagination_fields", RepairReversePaginationFieldsReducer),
  __reducerSchema("repair_scale_indexes", RepairScaleIndexesReducer),
  __reducerSchema("request_account_directory", RequestAccountDirectoryReducer),
  __reducerSchema("request_archive_batch", RequestArchiveBatchReducer),
  __reducerSchema("request_channel_directory", RequestChannelDirectoryReducer),
  __reducerSchema("request_conversation_members", RequestConversationMembersReducer),
  __reducerSchema("request_conversation_messages", RequestConversationMessagesReducer),
  __reducerSchema("request_conversations", RequestConversationsReducer),
  __reducerSchema("request_inbox_deliveries", RequestInboxDeliveriesReducer),
  __reducerSchema("reset_deployment_policy", ResetDeploymentPolicyReducer),
  __reducerSchema("reset_retention_policy", ResetRetentionPolicyReducer),
  __reducerSchema("revoke_capability", RevokeCapabilityReducer),
  __reducerSchema("run_retention_cleanup_now", RunRetentionCleanupNowReducer),
  __reducerSchema("send_conversation_message", SendConversationMessageReducer),
  __reducerSchema("send_direct_message", SendDirectMessageReducer),
  __reducerSchema("send_thread_message", SendThreadMessageReducer),
  __reducerSchema("set_account_type", SetAccountTypeReducer),
  __reducerSchema("set_deployment_policy", SetDeploymentPolicyReducer),
  __reducerSchema("set_profile", SetProfileReducer),
  __reducerSchema("set_retention_policy", SetRetentionPolicyReducer),
  __reducerSchema("set_room_config", SetRoomConfigReducer),
  __reducerSchema("set_room_role", SetRoomRoleReducer),
  __reducerSchema("unwatch_thread", UnwatchThreadReducer),
  __reducerSchema("update_task_status", UpdateTaskStatusReducer),
  __reducerSchema("watch_thread", WatchThreadReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.2.0" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

