// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  kind: __t.string(),
  endpointRef: __t.option(__t.string()),
  secretHash: __t.option(__t.string()),
  enabled: __t.option(__t.bool()),
  metadataJson: __t.option(__t.string()),
  agentId: __t.option(__t.string()),
  registrationId: __t.option(__t.string()),
};
