// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  conversationId: __t.u64(),
  text: __t.string(),
  kind: __t.string(),
  replyToMessageId: __t.option(__t.u64()),
  correlationId: __t.option(__t.string()),
  metadataJson: __t.option(__t.string()),
  artifactUrl: __t.option(__t.string()),
  artifactMimeType: __t.option(__t.string()),
  clientRequestId: __t.option(__t.string()),
};
