// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  targetAgentId: __t.option(__t.string()),
  targetIdentity: __t.option(__t.identity()),
  text: __t.string(),
  kind: __t.option(__t.string()),
  metadataJson: __t.option(__t.string()),
  correlationId: __t.option(__t.string()),
  clientRequestId: __t.option(__t.string()),
};
