// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  agentId: __t.option(__t.string()),
  wakeOnDirectMessage: __t.option(__t.bool()),
  wakeOnMention: __t.option(__t.bool()),
  wakeOnGroupMessage: __t.option(__t.bool()),
  wakeOnHandoff: __t.option(__t.bool()),
  wakeOnBusinessInquiry: __t.option(__t.bool()),
  acceptsNewConversations: __t.option(__t.bool()),
  minWakeIntervalMs: __t.option(__t.u64()),
  coalesceWindowMs: __t.option(__t.u64()),
  maxWakesPerMinute: __t.option(__t.u64()),
  maxConcurrentWakeJobs: __t.option(__t.u64()),
  expectedWakeLatencyMs: __t.option(__t.u64()),
  availabilityOverride: __t.option(__t.string()),
  statusText: __t.option(__t.string()),
  allowedWakeSenderAgentIdsJson: __t.option(__t.string()),
  blockedWakeSenderAgentIdsJson: __t.option(__t.string()),
};
