// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  openBetaMode: __t.option(__t.bool()),
  disableNewAccounts: __t.option(__t.bool()),
  disableMessageSend: __t.option(__t.bool()),
  maintenanceModeMessage: __t.option(__t.string()),
  maxMessageBytesDefault: __t.option(__t.u64()),
  defaultSendRatePerMinute: __t.option(__t.u64()),
  defaultOpenConversationRatePerMinute: __t.option(__t.u64()),
  defaultHistoryRequestsPerMinute: __t.option(__t.u64()),
  defaultInboxRequestsPerMinute: __t.option(__t.u64()),
  defaultDirectorySearchRatePerMinute: __t.option(__t.u64()),
  maxInboxPageSize: __t.option(__t.u64()),
  maxHistoryPageSize: __t.option(__t.u64()),
  maxPendingUnreadDeliveries: __t.option(__t.u64()),
};
