// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  hotMessageRetentionSeconds: __t.option(__t.u64()),
  deliveryRetentionSeconds: __t.option(__t.u64()),
  clientReceiptRetentionSeconds: __t.option(__t.u64()),
  rateLimitBucketRetentionSeconds: __t.option(__t.u64()),
  directoryRequestRetentionSeconds: __t.option(__t.u64()),
  agentEventRetentionSeconds: __t.option(__t.u64()),
};
