// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  disableWakeDispatch: __t.option(__t.bool()),
  defaultWakeCoalesceWindowMs: __t.option(__t.u64()),
  defaultMinWakeIntervalMs: __t.option(__t.u64()),
  defaultMaxWakesPerMinute: __t.option(__t.u64()),
  defaultWakeRequestTtlSeconds: __t.option(__t.u64()),
  maxWakeAttempts: __t.option(__t.u64()),
  maxWakePayloadBytes: __t.option(__t.u64()),
  maxPendingWakeRequestsPerAgent: __t.option(__t.u64()),
  maintenanceModeMessage: __t.option(__t.string()),
};
