// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Account = __t.object("Account", {
  handle: __t.string(),
  identity: __t.identity(),
  displayName: __t.string(),
  role: __t.string(),
  bio: __t.option(__t.string()),
  online: __t.bool(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
  lastSeen: __t.timestamp(),
  agentId: __t.option(__t.string()),
});
export type Account = __Infer<typeof Account>;

export const AccountDirectoryRequest = __t.object("AccountDirectoryRequest", {
  key: __t.string(),
  requesterIdentity: __t.identity(),
  query: __t.option(__t.string()),
  handle: __t.option(__t.string()),
  role: __t.option(__t.string()),
  online: __t.option(__t.bool()),
  limit: __t.u64(),
  updatedAt: __t.timestamp(),
});
export type AccountDirectoryRequest = __Infer<typeof AccountDirectoryRequest>;

export const AccountEntitlement = __t.object("AccountEntitlement", {
  handle: __t.string(),
  identity: __t.identity(),
  accountType: __t.string(),
  groupChatAllowed: __t.bool(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
  updatedBy: __t.option(__t.identity()),
  agentId: __t.option(__t.string()),
  maxGroupConversationMembers: __t.option(__t.u64()),
  maxMessageBytes: __t.option(__t.u64()),
  sendRatePerMinute: __t.option(__t.u64()),
  openConversationRatePerMinute: __t.option(__t.u64()),
  historyRequestRatePerMinute: __t.option(__t.u64()),
  inboxRequestRatePerMinute: __t.option(__t.u64()),
  directorySearchRatePerMinute: __t.option(__t.u64()),
  maxInboxPageSize: __t.option(__t.u64()),
  maxHistoryPageSize: __t.option(__t.u64()),
  maxPendingUnreadDeliveries: __t.option(__t.u64()),
});
export type AccountEntitlement = __Infer<typeof AccountEntitlement>;

export const AccountEntitlementLegacyView = __t.object("AccountEntitlementLegacyView", {
  handle: __t.string(),
  identity: __t.identity(),
  accountType: __t.string(),
  groupChatAllowed: __t.bool(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
  updatedBy: __t.option(__t.identity()),
  agentId: __t.option(__t.string()),
  maxGroupConversationMembers: __t.option(__t.u64()),
  maxMessageBytes: __t.option(__t.u64()),
  sendRatePerMinute: __t.option(__t.u64()),
});
export type AccountEntitlementLegacyView = __Infer<typeof AccountEntitlementLegacyView>;

export const ActiveConnection = __t.object("ActiveConnection", {
  connectionId: __t.connectionId(),
  identity: __t.identity(),
  agentId: __t.option(__t.string()),
  connectedAt: __t.timestamp(),
  lastSeen: __t.timestamp(),
});
export type ActiveConnection = __Infer<typeof ActiveConnection>;

export const AgentDeliveryCounter = __t.object("AgentDeliveryCounter", {
  agentId: __t.string(),
  unreadCount: __t.u64(),
  updatedAt: __t.timestamp(),
});
export type AgentDeliveryCounter = __Infer<typeof AgentDeliveryCounter>;

export const AgentDeliveryCounterView = __t.object("AgentDeliveryCounterView", {
  agentId: __t.string(),
  unreadCount: __t.u64(),
  updatedAt: __t.timestamp(),
});
export type AgentDeliveryCounterView = __Infer<typeof AgentDeliveryCounterView>;

export const AgentEvent = __t.object("AgentEvent", {
  id: __t.u64(),
  kind: __t.string(),
  actorIdentity: __t.identity(),
  channelId: __t.option(__t.u64()),
  threadId: __t.option(__t.u64()),
  conversationId: __t.option(__t.u64()),
  targetIdentity: __t.option(__t.identity()),
  text: __t.option(__t.string()),
  metadataJson: __t.option(__t.string()),
  emittedAt: __t.timestamp(),
});
export type AgentEvent = __Infer<typeof AgentEvent>;

export const AgentIdentity = __t.object("AgentIdentity", {
  identity: __t.identity(),
  agentId: __t.string(),
  deviceLabel: __t.option(__t.string()),
  status: __t.string(),
  createdAt: __t.timestamp(),
  lastSeen: __t.timestamp(),
  revokedAt: __t.option(__t.timestamp()),
});
export type AgentIdentity = __Infer<typeof AgentIdentity>;

export const AgentInstallation = __t.object("AgentInstallation", {
  identity: __t.identity(),
  ownerIdentity: __t.identity(),
  workspaceId: __t.option(__t.u64()),
  label: __t.string(),
  clientKind: __t.string(),
  status: __t.string(),
  createdAt: __t.timestamp(),
  expiresAt: __t.option(__t.timestamp()),
});
export type AgentInstallation = __Infer<typeof AgentInstallation>;

export const AgentProfile = __t.object("AgentProfile", {
  agentId: __t.string(),
  handle: __t.string(),
  displayName: __t.string(),
  role: __t.string(),
  bio: __t.option(__t.string()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
  lastSeen: __t.timestamp(),
  online: __t.bool(),
});
export type AgentProfile = __Infer<typeof AgentProfile>;

export const AgentSession = __t.object("AgentSession", {
  identity: __t.identity(),
  ownerIdentity: __t.identity(),
  workspaceId: __t.option(__t.u64()),
  clientKind: __t.string(),
  status: __t.string(),
  connectedAt: __t.timestamp(),
  lastSeen: __t.timestamp(),
});
export type AgentSession = __Infer<typeof AgentSession>;

export const AgentTask = __t.object("AgentTask", {
  id: __t.u64(),
  channelId: __t.u64(),
  title: __t.string(),
  description: __t.string(),
  status: __t.string(),
  priority: __t.string(),
  createdBy: __t.identity(),
  assignedTo: __t.option(__t.identity()),
  correlationId: __t.option(__t.string()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type AgentTask = __Infer<typeof AgentTask>;

export const ArchiveBatchRequest = __t.object("ArchiveBatchRequest", {
  key: __t.string(),
  requesterIdentity: __t.identity(),
  beforeSent: __t.option(__t.timestamp()),
  limit: __t.u64(),
  updatedAt: __t.timestamp(),
});
export type ArchiveBatchRequest = __Infer<typeof ArchiveBatchRequest>;

export const CapabilityGrant = __t.object("CapabilityGrant", {
  id: __t.u64(),
  granteeIdentity: __t.identity(),
  workspaceId: __t.option(__t.u64()),
  channelId: __t.option(__t.u64()),
  capability: __t.string(),
  grantedBy: __t.identity(),
  createdAt: __t.timestamp(),
  expiresAt: __t.option(__t.timestamp()),
  revokedAt: __t.option(__t.timestamp()),
});
export type CapabilityGrant = __Infer<typeof CapabilityGrant>;

export const Channel = __t.object("Channel", {
  id: __t.u64(),
  name: __t.string(),
  topic: __t.string(),
  createdBy: __t.option(__t.identity()),
  createdAt: __t.timestamp(),
});
export type Channel = __Infer<typeof Channel>;

export const ChannelDirectoryRequest = __t.object("ChannelDirectoryRequest", {
  key: __t.string(),
  requesterIdentity: __t.identity(),
  query: __t.option(__t.string()),
  name: __t.option(__t.string()),
  limit: __t.u64(),
  updatedAt: __t.timestamp(),
});
export type ChannelDirectoryRequest = __Infer<typeof ChannelDirectoryRequest>;

export const ChannelMember = __t.object("ChannelMember", {
  id: __t.u64(),
  channelId: __t.u64(),
  memberIdentity: __t.identity(),
  joinedAt: __t.timestamp(),
});
export type ChannelMember = __Infer<typeof ChannelMember>;

export const ChannelRole = __t.object("ChannelRole", {
  key: __t.string(),
  channelId: __t.u64(),
  memberIdentity: __t.identity(),
  role: __t.string(),
  setBy: __t.option(__t.identity()),
  updatedAt: __t.timestamp(),
});
export type ChannelRole = __Infer<typeof ChannelRole>;

export const ChannelWorkspace = __t.object("ChannelWorkspace", {
  id: __t.u64(),
  channelId: __t.u64(),
  workspaceId: __t.u64(),
  linkedAt: __t.timestamp(),
});
export type ChannelWorkspace = __Infer<typeof ChannelWorkspace>;

export const ClientRequestReceipt = __t.object("ClientRequestReceipt", {
  key: __t.string(),
  senderAgentId: __t.string(),
  senderIdentity: __t.identity(),
  action: __t.string(),
  clientRequestId: __t.string(),
  status: __t.string(),
  conversationId: __t.option(__t.u64()),
  messageId: __t.option(__t.u64()),
  sequence: __t.option(__t.u64()),
  error: __t.option(__t.string()),
  createdAt: __t.timestamp(),
  expiresAt: __t.timestamp(),
});
export type ClientRequestReceipt = __Infer<typeof ClientRequestReceipt>;

export const Conversation = __t.object("Conversation", {
  id: __t.u64(),
  kind: __t.string(),
  title: __t.string(),
  createdBy: __t.identity(),
  createdAt: __t.timestamp(),
  lastActivity: __t.timestamp(),
});
export type Conversation = __Infer<typeof Conversation>;

export const ConversationDelivery = __t.object("ConversationDelivery", {
  key: __t.string(),
  recipientAgentId: __t.string(),
  recipientIdentity: __t.option(__t.identity()),
  conversationId: __t.u64(),
  messageId: __t.u64(),
  sequence: __t.u64(),
  senderAgentId: __t.string(),
  senderIdentity: __t.identity(),
  state: __t.string(),
  sent: __t.timestamp(),
  updatedAt: __t.timestamp(),
  expiresAt: __t.timestamp(),
  reverseSentMicros: __t.u64(),
  reverseSequence: __t.u64(),
});
export type ConversationDelivery = __Infer<typeof ConversationDelivery>;

export const ConversationDeliveryLegacyView = __t.object("ConversationDeliveryLegacyView", {
  key: __t.string(),
  recipientAgentId: __t.string(),
  recipientIdentity: __t.option(__t.identity()),
  conversationId: __t.u64(),
  messageId: __t.u64(),
  sequence: __t.u64(),
  senderAgentId: __t.string(),
  senderIdentity: __t.identity(),
  state: __t.string(),
  sent: __t.timestamp(),
  updatedAt: __t.timestamp(),
  expiresAt: __t.timestamp(),
});
export type ConversationDeliveryLegacyView = __Infer<typeof ConversationDeliveryLegacyView>;

export const ConversationListRequest = __t.object("ConversationListRequest", {
  key: __t.string(),
  requesterIdentity: __t.identity(),
  kind: __t.option(__t.string()),
  beforeLastActivity: __t.option(__t.timestamp()),
  limit: __t.u64(),
  updatedAt: __t.timestamp(),
});
export type ConversationListRequest = __Infer<typeof ConversationListRequest>;

export const ConversationMember = __t.object("ConversationMember", {
  id: __t.u64(),
  conversationId: __t.u64(),
  memberIdentity: __t.identity(),
  role: __t.string(),
  joinedAt: __t.timestamp(),
  memberAgentId: __t.option(__t.string()),
});
export type ConversationMember = __Infer<typeof ConversationMember>;

export const ConversationMemberRequest = __t.object("ConversationMemberRequest", {
  key: __t.string(),
  requesterIdentity: __t.identity(),
  conversationId: __t.u64(),
  updatedAt: __t.timestamp(),
});
export type ConversationMemberRequest = __Infer<typeof ConversationMemberRequest>;

export const ConversationMessage = __t.object("ConversationMessage", {
  id: __t.u64(),
  conversationId: __t.u64(),
  authorIdentity: __t.identity(),
  authorLabel: __t.string(),
  authorKind: __t.string(),
  kind: __t.string(),
  text: __t.string(),
  replyToMessageId: __t.option(__t.u64()),
  correlationId: __t.option(__t.string()),
  clientRequestId: __t.option(__t.string()),
  metadataJson: __t.option(__t.string()),
  artifactUrl: __t.option(__t.string()),
  artifactMimeType: __t.option(__t.string()),
  sent: __t.timestamp(),
  sequence: __t.u64(),
  expiresAt: __t.timestamp(),
  archiveStatus: __t.string(),
  archivedAt: __t.option(__t.timestamp()),
  reverseSequence: __t.u64(),
});
export type ConversationMessage = __Infer<typeof ConversationMessage>;

export const ConversationMessageLegacyView = __t.object("ConversationMessageLegacyView", {
  id: __t.u64(),
  conversationId: __t.u64(),
  authorIdentity: __t.identity(),
  authorLabel: __t.string(),
  authorKind: __t.string(),
  kind: __t.string(),
  text: __t.string(),
  replyToMessageId: __t.option(__t.u64()),
  correlationId: __t.option(__t.string()),
  clientRequestId: __t.option(__t.string()),
  metadataJson: __t.option(__t.string()),
  artifactUrl: __t.option(__t.string()),
  artifactMimeType: __t.option(__t.string()),
  sent: __t.timestamp(),
  sequence: __t.u64(),
  expiresAt: __t.timestamp(),
  archiveStatus: __t.string(),
  archivedAt: __t.option(__t.timestamp()),
});
export type ConversationMessageLegacyView = __Infer<typeof ConversationMessageLegacyView>;

export const ConversationMessageRequest = __t.object("ConversationMessageRequest", {
  key: __t.string(),
  requesterIdentity: __t.identity(),
  conversationId: __t.u64(),
  afterSequence: __t.option(__t.u64()),
  beforeSequence: __t.option(__t.u64()),
  limit: __t.u64(),
  updatedAt: __t.timestamp(),
});
export type ConversationMessageRequest = __Infer<typeof ConversationMessageRequest>;

export const ConversationParticipantIndex = __t.object("ConversationParticipantIndex", {
  key: __t.string(),
  agentId: __t.string(),
  memberIdentity: __t.identity(),
  conversationId: __t.u64(),
  role: __t.string(),
  kind: __t.string(),
  title: __t.string(),
  lastActivity: __t.timestamp(),
  reverseLastActivityMicros: __t.u64(),
  lastSequence: __t.u64(),
  lastReadSequence: __t.u64(),
  unreadCount: __t.u64(),
  active: __t.bool(),
  joinedAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type ConversationParticipantIndex = __Infer<typeof ConversationParticipantIndex>;

export const ConversationParticipantSummaryView = __t.object("ConversationParticipantSummaryView", {
  key: __t.string(),
  agentId: __t.string(),
  conversationId: __t.u64(),
  role: __t.string(),
  kind: __t.string(),
  title: __t.string(),
  lastActivity: __t.timestamp(),
  lastSequence: __t.u64(),
  lastReadSequence: __t.u64(),
  unreadCount: __t.u64(),
  active: __t.bool(),
  joinedAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type ConversationParticipantSummaryView = __Infer<typeof ConversationParticipantSummaryView>;

export const ConversationReadCursor = __t.object("ConversationReadCursor", {
  key: __t.string(),
  conversationId: __t.u64(),
  memberIdentity: __t.identity(),
  lastReadSequence: __t.u64(),
  updatedAt: __t.timestamp(),
});
export type ConversationReadCursor = __Infer<typeof ConversationReadCursor>;

export const ConversationSequence = __t.object("ConversationSequence", {
  conversationId: __t.u64(),
  nextSequence: __t.u64(),
  updatedAt: __t.timestamp(),
});
export type ConversationSequence = __Infer<typeof ConversationSequence>;

export const DeploymentPolicy = __t.object("DeploymentPolicy", {
  key: __t.string(),
  openBetaMode: __t.bool(),
  disableNewAccounts: __t.bool(),
  disableMessageSend: __t.bool(),
  maintenanceModeMessage: __t.option(__t.string()),
  maxMessageBytesDefault: __t.u64(),
  defaultSendRatePerMinute: __t.u64(),
  defaultOpenConversationRatePerMinute: __t.u64(),
  defaultHistoryRequestsPerMinute: __t.u64(),
  defaultInboxRequestsPerMinute: __t.u64(),
  defaultDirectorySearchRatePerMinute: __t.u64(),
  maxInboxPageSize: __t.u64(),
  maxHistoryPageSize: __t.u64(),
  maxPendingUnreadDeliveries: __t.u64(),
  updatedAt: __t.timestamp(),
  updatedBy: __t.option(__t.identity()),
});
export type DeploymentPolicy = __Infer<typeof DeploymentPolicy>;

export const DeploymentPolicyView = __t.object("DeploymentPolicyView", {
  key: __t.string(),
  openBetaMode: __t.bool(),
  disableNewAccounts: __t.bool(),
  disableMessageSend: __t.bool(),
  maintenanceModeMessage: __t.option(__t.string()),
  maxMessageBytesDefault: __t.u64(),
  defaultSendRatePerMinute: __t.u64(),
  defaultOpenConversationRatePerMinute: __t.u64(),
  defaultHistoryRequestsPerMinute: __t.u64(),
  defaultInboxRequestsPerMinute: __t.u64(),
  defaultDirectorySearchRatePerMinute: __t.u64(),
  maxInboxPageSize: __t.u64(),
  maxHistoryPageSize: __t.u64(),
  maxPendingUnreadDeliveries: __t.u64(),
  updatedAt: __t.timestamp(),
});
export type DeploymentPolicyView = __Infer<typeof DeploymentPolicyView>;

export const DirectConversationIndex = __t.object("DirectConversationIndex", {
  pairKey: __t.string(),
  leftAgentId: __t.string(),
  rightAgentId: __t.string(),
  conversationId: __t.u64(),
  createdAt: __t.timestamp(),
});
export type DirectConversationIndex = __Infer<typeof DirectConversationIndex>;

export const Handoff = __t.object("Handoff", {
  id: __t.u64(),
  channelId: __t.u64(),
  fromIdentity: __t.identity(),
  toIdentity: __t.option(__t.identity()),
  summary: __t.string(),
  contextJson: __t.option(__t.string()),
  status: __t.string(),
  createdAt: __t.timestamp(),
  acceptedAt: __t.option(__t.timestamp()),
});
export type Handoff = __Infer<typeof Handoff>;

export const InboxDeliveryRequest = __t.object("InboxDeliveryRequest", {
  key: __t.string(),
  requesterIdentity: __t.identity(),
  requesterAgentId: __t.string(),
  state: __t.option(__t.string()),
  conversationId: __t.option(__t.u64()),
  afterSequence: __t.option(__t.u64()),
  beforeSent: __t.option(__t.timestamp()),
  limit: __t.u64(),
  updatedAt: __t.timestamp(),
});
export type InboxDeliveryRequest = __Infer<typeof InboxDeliveryRequest>;

export const Message = __t.object("Message", {
  id: __t.u64(),
  channelId: __t.u64(),
  threadId: __t.u64(),
  authorIdentity: __t.option(__t.identity()),
  authorLabel: __t.string(),
  authorKind: __t.string(),
  text: __t.string(),
  sent: __t.timestamp(),
});
export type Message = __Infer<typeof Message>;

export const OperatorScaleSnapshotView = __t.object("OperatorScaleSnapshotView", {
  key: __t.string(),
  capturedAt: __t.timestamp(),
  activeConnections: __t.u64(),
  activeConnectionAgents: __t.u64(),
  activeAccounts: __t.u64(),
  activeAgentProfiles: __t.u64(),
  conversationCount: __t.u64(),
  conversationMemberCount: __t.u64(),
  conversationDeliveryCount: __t.u64(),
  unreadDeliveryCount: __t.u64(),
  agentDeliveryCounterUnreadTotal: __t.u64(),
  conversationParticipantIndexCount: __t.u64(),
  requestRowCount: __t.u64(),
  rateLimitBucketCount: __t.u64(),
  cleanupCapped: __t.bool(),
  lastCleanupRunAt: __t.timestamp(),
  deploymentDisableNewAccounts: __t.bool(),
  deploymentDisableMessageSend: __t.bool(),
});
export type OperatorScaleSnapshotView = __Infer<typeof OperatorScaleSnapshotView>;

export const Principal = __t.object("Principal", {
  identity: __t.identity(),
  ownerIdentity: __t.option(__t.identity()),
  kind: __t.string(),
  displayName: __t.option(__t.string()),
  createdAt: __t.timestamp(),
  lastSeen: __t.timestamp(),
});
export type Principal = __Infer<typeof Principal>;

export const PublicAccountDirectory = __t.object("PublicAccountDirectory", {});
export type PublicAccountDirectory = __Infer<typeof PublicAccountDirectory>;

export const PublicChannelDirectory = __t.object("PublicChannelDirectory", {});
export type PublicChannelDirectory = __Infer<typeof PublicChannelDirectory>;

export const RateLimitBucket = __t.object("RateLimitBucket", {
  bucketKey: __t.string(),
  senderIdentity: __t.identity(),
  action: __t.string(),
  bucket: __t.u64(),
  count: __t.u64(),
  updatedAt: __t.timestamp(),
});
export type RateLimitBucket = __Infer<typeof RateLimitBucket>;

export const RateLimitPressureView = __t.object("RateLimitPressureView", {
  key: __t.string(),
  action: __t.string(),
  bucketCount: __t.u64(),
  totalCount: __t.u64(),
  maxBucketCount: __t.u64(),
  latestUpdatedAt: __t.timestamp(),
});
export type RateLimitPressureView = __Infer<typeof RateLimitPressureView>;

export const RequestLog = __t.object("RequestLog", {
  requestKey: __t.string(),
  senderIdentity: __t.identity(),
  action: __t.string(),
  createdAt: __t.timestamp(),
});
export type RequestLog = __Infer<typeof RequestLog>;

export const RetentionCleanupJob = __t.object("RetentionCleanupJob", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  reason: __t.string(),
});
export type RetentionCleanupJob = __Infer<typeof RetentionCleanupJob>;

export const RetentionCleanupStat = __t.object("RetentionCleanupStat", {
  key: __t.string(),
  lastRunAt: __t.timestamp(),
  reason: __t.string(),
  deliveryDeleted: __t.u64(),
  receiptDeleted: __t.u64(),
  accountDirectoryRequestDeleted: __t.u64(),
  channelDirectoryRequestDeleted: __t.u64(),
  conversationMessageRequestDeleted: __t.u64(),
  archiveBatchRequestDeleted: __t.u64(),
  rateLimitBucketDeleted: __t.u64(),
  requestLogDeleted: __t.u64(),
  agentEventDeleted: __t.u64(),
  conversationMessageDeleted: __t.u64(),
  capped: __t.bool(),
  inboxDeliveryRequestDeleted: __t.u64(),
  conversationListRequestDeleted: __t.u64(),
  conversationMemberRequestDeleted: __t.u64(),
  expiredDeliveryBacklogRemaining: __t.u64(),
  expiredReceiptBacklogRemaining: __t.u64(),
  staleRequestBacklogRemaining: __t.u64(),
  staleRateLimitBucketBacklogRemaining: __t.u64(),
  expiredMessageBacklogRemaining: __t.u64(),
  durationMicros: __t.u64(),
  nextScheduledAt: __t.option(__t.timestamp()),
});
export type RetentionCleanupStat = __Infer<typeof RetentionCleanupStat>;

export const RetentionCleanupStatLegacyView = __t.object("RetentionCleanupStatLegacyView", {
  key: __t.string(),
  lastRunAt: __t.timestamp(),
  reason: __t.string(),
  deliveryDeleted: __t.u64(),
  receiptDeleted: __t.u64(),
  accountDirectoryRequestDeleted: __t.u64(),
  channelDirectoryRequestDeleted: __t.u64(),
  conversationMessageRequestDeleted: __t.u64(),
  archiveBatchRequestDeleted: __t.u64(),
  rateLimitBucketDeleted: __t.u64(),
  requestLogDeleted: __t.u64(),
  agentEventDeleted: __t.u64(),
  conversationMessageDeleted: __t.u64(),
  capped: __t.bool(),
});
export type RetentionCleanupStatLegacyView = __Infer<typeof RetentionCleanupStatLegacyView>;

export const RetentionPolicy = __t.object("RetentionPolicy", {
  key: __t.string(),
  hotMessageRetentionSeconds: __t.u64(),
  deliveryRetentionSeconds: __t.u64(),
  clientReceiptRetentionSeconds: __t.u64(),
  rateLimitBucketRetentionSeconds: __t.u64(),
  directoryRequestRetentionSeconds: __t.u64(),
  agentEventRetentionSeconds: __t.u64(),
  updatedAt: __t.timestamp(),
  updatedBy: __t.identity(),
});
export type RetentionPolicy = __Infer<typeof RetentionPolicy>;

export const RetentionPolicyView = __t.object("RetentionPolicyView", {
  key: __t.string(),
  hotMessageRetentionSeconds: __t.u64(),
  hotRetentionHours: __t.u64(),
  deliveryRetentionSeconds: __t.u64(),
  clientReceiptRetentionSeconds: __t.u64(),
  archiveRequiredBeforePurge: __t.bool(),
  archiveConfigured: __t.bool(),
});
export type RetentionPolicyView = __Infer<typeof RetentionPolicyView>;

export const RevokedIdentity = __t.object("RevokedIdentity", {
  identity: __t.identity(),
  reason: __t.string(),
  revokedBy: __t.option(__t.identity()),
  revokedAt: __t.timestamp(),
});
export type RevokedIdentity = __Infer<typeof RevokedIdentity>;

export const RichMessage = __t.object("RichMessage", {
  id: __t.u64(),
  legacyMessageId: __t.option(__t.u64()),
  channelId: __t.u64(),
  threadId: __t.u64(),
  authorIdentity: __t.option(__t.identity()),
  authorLabel: __t.string(),
  authorKind: __t.string(),
  kind: __t.string(),
  text: __t.string(),
  replyToMessageId: __t.option(__t.u64()),
  correlationId: __t.option(__t.string()),
  clientRequestId: __t.option(__t.string()),
  metadataJson: __t.option(__t.string()),
  artifactUrl: __t.option(__t.string()),
  artifactMimeType: __t.option(__t.string()),
  sent: __t.timestamp(),
});
export type RichMessage = __Infer<typeof RichMessage>;

export const RoomConfig = __t.object("RoomConfig", {
  channelId: __t.u64(),
  ownerIdentity: __t.identity(),
  visibility: __t.string(),
  joinPolicy: __t.string(),
  password: __t.option(__t.string()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type RoomConfig = __Infer<typeof RoomConfig>;

export const RoomRemovalReceipt = __t.object("RoomRemovalReceipt", {
  id: __t.u64(),
  channelId: __t.u64(),
  channelName: __t.string(),
  removedIdentity: __t.identity(),
  removedBy: __t.identity(),
  reason: __t.string(),
  removedAt: __t.timestamp(),
});
export type RoomRemovalReceipt = __Infer<typeof RoomRemovalReceipt>;

export const ScaleRepairStat = __t.object("ScaleRepairStat", {
  key: __t.string(),
  lastRunAt: __t.timestamp(),
  reason: __t.string(),
  reverseMessageUpdated: __t.u64(),
  reverseDeliveryUpdated: __t.u64(),
  deliveryCounterUpdated: __t.u64(),
  participantIndexUpdated: __t.u64(),
  capped: __t.bool(),
});
export type ScaleRepairStat = __Infer<typeof ScaleRepairStat>;

export const ScaleRepairStatView = __t.object("ScaleRepairStatView", {
  key: __t.string(),
  lastRunAt: __t.timestamp(),
  reason: __t.string(),
  reverseMessageUpdated: __t.u64(),
  reverseDeliveryUpdated: __t.u64(),
  deliveryCounterUpdated: __t.u64(),
  participantIndexUpdated: __t.u64(),
  capped: __t.bool(),
});
export type ScaleRepairStatView = __Infer<typeof ScaleRepairStatView>;

export const TaskClaim = __t.object("TaskClaim", {
  id: __t.u64(),
  taskId: __t.u64(),
  claimantIdentity: __t.identity(),
  status: __t.string(),
  claimedAt: __t.timestamp(),
  releasedAt: __t.option(__t.timestamp()),
});
export type TaskClaim = __Infer<typeof TaskClaim>;

export const Thread = __t.object("Thread", {
  id: __t.u64(),
  channelId: __t.u64(),
  title: __t.string(),
  createdBy: __t.option(__t.identity()),
  createdAt: __t.timestamp(),
  lastActivity: __t.timestamp(),
});
export type Thread = __Infer<typeof Thread>;

export const ThreadWatch = __t.object("ThreadWatch", {
  id: __t.u64(),
  watcherIdentity: __t.identity(),
  threadId: __t.u64(),
  channelId: __t.u64(),
  lastSeenMessageId: __t.option(__t.u64()),
  watchedAt: __t.timestamp(),
});
export type ThreadWatch = __Infer<typeof ThreadWatch>;

export const User = __t.object("User", {
  identity: __t.identity(),
  name: __t.option(__t.string()),
  role: __t.string(),
  bio: __t.option(__t.string()),
  online: __t.bool(),
  lastSeen: __t.timestamp(),
});
export type User = __Infer<typeof User>;

export const VisibleAccount = __t.object("VisibleAccount", {});
export type VisibleAccount = __Infer<typeof VisibleAccount>;

export const VisibleAccountEntitlement = __t.object("VisibleAccountEntitlement", {});
export type VisibleAccountEntitlement = __Infer<typeof VisibleAccountEntitlement>;

export const VisibleAgentDeliveryCounter = __t.object("VisibleAgentDeliveryCounter", {});
export type VisibleAgentDeliveryCounter = __Infer<typeof VisibleAgentDeliveryCounter>;

export const VisibleAgentEvent = __t.object("VisibleAgentEvent", {});
export type VisibleAgentEvent = __Infer<typeof VisibleAgentEvent>;

export const VisibleAgentProfile = __t.object("VisibleAgentProfile", {});
export type VisibleAgentProfile = __Infer<typeof VisibleAgentProfile>;

export const VisibleAgentSession = __t.object("VisibleAgentSession", {});
export type VisibleAgentSession = __Infer<typeof VisibleAgentSession>;

export const VisibleArchiveCandidateMessage = __t.object("VisibleArchiveCandidateMessage", {});
export type VisibleArchiveCandidateMessage = __Infer<typeof VisibleArchiveCandidateMessage>;

export const VisibleCapabilityGrant = __t.object("VisibleCapabilityGrant", {});
export type VisibleCapabilityGrant = __Infer<typeof VisibleCapabilityGrant>;

export const VisibleChannel = __t.object("VisibleChannel", {});
export type VisibleChannel = __Infer<typeof VisibleChannel>;

export const VisibleChannelMember = __t.object("VisibleChannelMember", {});
export type VisibleChannelMember = __Infer<typeof VisibleChannelMember>;

export const VisibleChannelRole = __t.object("VisibleChannelRole", {});
export type VisibleChannelRole = __Infer<typeof VisibleChannelRole>;

export const VisibleClientRequestReceipt = __t.object("VisibleClientRequestReceipt", {});
export type VisibleClientRequestReceipt = __Infer<typeof VisibleClientRequestReceipt>;

export const VisibleConversation = __t.object("VisibleConversation", {});
export type VisibleConversation = __Infer<typeof VisibleConversation>;

export const VisibleConversationMember = __t.object("VisibleConversationMember", {});
export type VisibleConversationMember = __Infer<typeof VisibleConversationMember>;

export const VisibleConversationMessage = __t.object("VisibleConversationMessage", {});
export type VisibleConversationMessage = __Infer<typeof VisibleConversationMessage>;

export const VisibleConversationReadCursor = __t.object("VisibleConversationReadCursor", {});
export type VisibleConversationReadCursor = __Infer<typeof VisibleConversationReadCursor>;

export const VisibleDeploymentPolicy = __t.object("VisibleDeploymentPolicy", {});
export type VisibleDeploymentPolicy = __Infer<typeof VisibleDeploymentPolicy>;

export const VisibleDirectConversation = __t.object("VisibleDirectConversation", {});
export type VisibleDirectConversation = __Infer<typeof VisibleDirectConversation>;

export const VisibleHandoff = __t.object("VisibleHandoff", {});
export type VisibleHandoff = __Infer<typeof VisibleHandoff>;

export const VisibleInboxDelivery = __t.object("VisibleInboxDelivery", {});
export type VisibleInboxDelivery = __Infer<typeof VisibleInboxDelivery>;

export const VisibleMessage = __t.object("VisibleMessage", {});
export type VisibleMessage = __Infer<typeof VisibleMessage>;

export const VisibleOperatorScaleSnapshot = __t.object("VisibleOperatorScaleSnapshot", {});
export type VisibleOperatorScaleSnapshot = __Infer<typeof VisibleOperatorScaleSnapshot>;

export const VisibleRateLimitBucket = __t.object("VisibleRateLimitBucket", {});
export type VisibleRateLimitBucket = __Infer<typeof VisibleRateLimitBucket>;

export const VisibleRateLimitPressure = __t.object("VisibleRateLimitPressure", {});
export type VisibleRateLimitPressure = __Infer<typeof VisibleRateLimitPressure>;

export const VisibleRequestedAccountDirectory = __t.object("VisibleRequestedAccountDirectory", {});
export type VisibleRequestedAccountDirectory = __Infer<typeof VisibleRequestedAccountDirectory>;

export const VisibleRequestedChannelDirectory = __t.object("VisibleRequestedChannelDirectory", {});
export type VisibleRequestedChannelDirectory = __Infer<typeof VisibleRequestedChannelDirectory>;

export const VisibleRequestedConversation = __t.object("VisibleRequestedConversation", {});
export type VisibleRequestedConversation = __Infer<typeof VisibleRequestedConversation>;

export const VisibleRequestedConversationMember = __t.object("VisibleRequestedConversationMember", {});
export type VisibleRequestedConversationMember = __Infer<typeof VisibleRequestedConversationMember>;

export const VisibleRequestedConversationMessage = __t.object("VisibleRequestedConversationMessage", {});
export type VisibleRequestedConversationMessage = __Infer<typeof VisibleRequestedConversationMessage>;

export const VisibleRequestedConversationSummary = __t.object("VisibleRequestedConversationSummary", {});
export type VisibleRequestedConversationSummary = __Infer<typeof VisibleRequestedConversationSummary>;

export const VisibleRequestedInboxDelivery = __t.object("VisibleRequestedInboxDelivery", {});
export type VisibleRequestedInboxDelivery = __Infer<typeof VisibleRequestedInboxDelivery>;

export const VisibleRetentionCleanupStat = __t.object("VisibleRetentionCleanupStat", {});
export type VisibleRetentionCleanupStat = __Infer<typeof VisibleRetentionCleanupStat>;

export const VisibleRetentionPolicy = __t.object("VisibleRetentionPolicy", {});
export type VisibleRetentionPolicy = __Infer<typeof VisibleRetentionPolicy>;

export const VisibleRichMessage = __t.object("VisibleRichMessage", {});
export type VisibleRichMessage = __Infer<typeof VisibleRichMessage>;

export const VisibleRoomConfig = __t.object("VisibleRoomConfig", {});
export type VisibleRoomConfig = __Infer<typeof VisibleRoomConfig>;

export const VisibleRoomRemovalReceipt = __t.object("VisibleRoomRemovalReceipt", {});
export type VisibleRoomRemovalReceipt = __Infer<typeof VisibleRoomRemovalReceipt>;

export const VisibleScaleRepairStat = __t.object("VisibleScaleRepairStat", {});
export type VisibleScaleRepairStat = __Infer<typeof VisibleScaleRepairStat>;

export const VisibleSelfAgentProfile = __t.object("VisibleSelfAgentProfile", {});
export type VisibleSelfAgentProfile = __Infer<typeof VisibleSelfAgentProfile>;

export const VisibleTask = __t.object("VisibleTask", {});
export type VisibleTask = __Infer<typeof VisibleTask>;

export const VisibleTaskClaim = __t.object("VisibleTaskClaim", {});
export type VisibleTaskClaim = __Infer<typeof VisibleTaskClaim>;

export const VisibleThread = __t.object("VisibleThread", {});
export type VisibleThread = __Infer<typeof VisibleThread>;

export const VisibleThreadWatch = __t.object("VisibleThreadWatch", {});
export type VisibleThreadWatch = __Infer<typeof VisibleThreadWatch>;

export const VisibleUnreadConversationMessage = __t.object("VisibleUnreadConversationMessage", {});
export type VisibleUnreadConversationMessage = __Infer<typeof VisibleUnreadConversationMessage>;

export const VisibleUser = __t.object("VisibleUser", {});
export type VisibleUser = __Infer<typeof VisibleUser>;

export const VisibleWatchedMessage = __t.object("VisibleWatchedMessage", {});
export type VisibleWatchedMessage = __Infer<typeof VisibleWatchedMessage>;

export const VisibleWorkspace = __t.object("VisibleWorkspace", {});
export type VisibleWorkspace = __Infer<typeof VisibleWorkspace>;

export const VisibleWorkspaceChannel = __t.object("VisibleWorkspaceChannel", {});
export type VisibleWorkspaceChannel = __Infer<typeof VisibleWorkspaceChannel>;

export const VisibleWorkspaceMember = __t.object("VisibleWorkspaceMember", {});
export type VisibleWorkspaceMember = __Infer<typeof VisibleWorkspaceMember>;

export const Workspace = __t.object("Workspace", {
  id: __t.u64(),
  slug: __t.string(),
  name: __t.string(),
  createdBy: __t.option(__t.identity()),
  createdAt: __t.timestamp(),
});
export type Workspace = __Infer<typeof Workspace>;

export const WorkspaceInvite = __t.object("WorkspaceInvite", {
  code: __t.string(),
  workspaceId: __t.u64(),
  workspaceRole: __t.string(),
  createdBy: __t.identity(),
  maxUses: __t.u64(),
  acceptedUses: __t.u64(),
  createdAt: __t.timestamp(),
  expiresAt: __t.option(__t.timestamp()),
  revokedAt: __t.option(__t.timestamp()),
});
export type WorkspaceInvite = __Infer<typeof WorkspaceInvite>;

export const WorkspaceMember = __t.object("WorkspaceMember", {
  id: __t.u64(),
  workspaceId: __t.u64(),
  memberIdentity: __t.identity(),
  role: __t.string(),
  joinedAt: __t.timestamp(),
});
export type WorkspaceMember = __Infer<typeof WorkspaceMember>;

