// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  key: __t.string(),
  disableWakeDispatch: __t.bool().name("disable_wake_dispatch"),
  defaultWakeCoalesceWindowMs: __t.u64().name("default_wake_coalesce_window_ms"),
  defaultMinWakeIntervalMs: __t.u64().name("default_min_wake_interval_ms"),
  defaultMaxWakesPerMinute: __t.u64().name("default_max_wakes_per_minute"),
  defaultWakeRequestTtlSeconds: __t.u64().name("default_wake_request_ttl_seconds"),
  maxWakeAttempts: __t.u64().name("max_wake_attempts"),
  maxWakePayloadBytes: __t.u64().name("max_wake_payload_bytes"),
  maxPendingWakeRequestsPerAgent: __t.u64().name("max_pending_wake_requests_per_agent"),
  maintenanceModeMessage: __t.option(__t.string()).name("maintenance_mode_message"),
  updatedAt: __t.timestamp().name("updated_at"),
});
