// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  agentId: __t.string().name("agent_id"),
  wakeOnDirectMessage: __t.bool().name("wake_on_direct_message"),
  wakeOnMention: __t.bool().name("wake_on_mention"),
  wakeOnGroupMessage: __t.bool().name("wake_on_group_message"),
  wakeOnHandoff: __t.bool().name("wake_on_handoff"),
  wakeOnBusinessInquiry: __t.bool().name("wake_on_business_inquiry"),
  acceptsNewConversations: __t.bool().name("accepts_new_conversations"),
  minWakeIntervalMs: __t.u64().name("min_wake_interval_ms"),
  coalesceWindowMs: __t.u64().name("coalesce_window_ms"),
  maxWakesPerMinute: __t.u64().name("max_wakes_per_minute"),
  maxConcurrentWakeJobs: __t.u64().name("max_concurrent_wake_jobs"),
  expectedWakeLatencyMs: __t.option(__t.u64()).name("expected_wake_latency_ms"),
  availabilityOverride: __t.option(__t.string()).name("availability_override"),
  statusText: __t.option(__t.string()).name("status_text"),
  allowedWakeSenderAgentIdsJson: __t.option(__t.string()).name("allowed_wake_sender_agent_ids_json"),
  blockedWakeSenderAgentIdsJson: __t.option(__t.string()).name("blocked_wake_sender_agent_ids_json"),
  updatedAt: __t.timestamp().name("updated_at"),
  updatedBy: __t.identity().name("updated_by"),
});
