// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  registrationId: __t.string().name("registration_id"),
  agentId: __t.string().name("agent_id"),
  ownerIdentity: __t.identity().name("owner_identity"),
  kind: __t.string(),
  endpointRef: __t.option(__t.string()).name("endpoint_ref"),
  secretConfigured: __t.bool().name("secret_configured"),
  enabled: __t.bool(),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
  lastSuccessAt: __t.option(__t.timestamp()).name("last_success_at"),
  lastFailureAt: __t.option(__t.timestamp()).name("last_failure_at"),
  failureCount: __t.u64().name("failure_count"),
  metadataJson: __t.option(__t.string()).name("metadata_json"),
});
