// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  key: __t.string(),
  action: __t.string(),
  bucketCount: __t.u64().name("bucket_count"),
  totalCount: __t.u64().name("total_count"),
  maxBucketCount: __t.u64().name("max_bucket_count"),
  latestUpdatedAt: __t.timestamp().name("latest_updated_at"),
});
