// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  key: __t.string(),
  senderAgentId: __t.string().name("sender_agent_id"),
  senderIdentity: __t.identity().name("sender_identity"),
  action: __t.string(),
  clientRequestId: __t.string().name("client_request_id"),
  status: __t.string(),
  conversationId: __t.option(__t.u64()).name("conversation_id"),
  messageId: __t.option(__t.u64()).name("message_id"),
  sequence: __t.option(__t.u64()),
  error: __t.option(__t.string()),
  createdAt: __t.timestamp().name("created_at"),
  expiresAt: __t.timestamp().name("expires_at"),
});
