// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64(),
  kind: __t.string(),
  actorIdentity: __t.identity().name("actor_identity"),
  channelId: __t.option(__t.u64()).name("channel_id"),
  threadId: __t.option(__t.u64()).name("thread_id"),
  conversationId: __t.option(__t.u64()).name("conversation_id"),
  targetIdentity: __t.option(__t.identity()).name("target_identity"),
  text: __t.option(__t.string()),
  metadataJson: __t.option(__t.string()).name("metadata_json"),
  emittedAt: __t.timestamp().name("emitted_at"),
});
