// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  wakeId: __t.string().name("wake_id"),
  wakeKey: __t.string().name("wake_key"),
  recipientAgentId: __t.string().name("recipient_agent_id"),
  recipientIdentity: __t.option(__t.identity()).name("recipient_identity"),
  senderAgentId: __t.string().name("sender_agent_id"),
  conversationId: __t.u64().name("conversation_id"),
  minSequence: __t.u64().name("min_sequence"),
  maxSequence: __t.u64().name("max_sequence"),
  reason: __t.string(),
  status: __t.string(),
  priority: __t.string(),
  attemptCount: __t.u64().name("attempt_count"),
  nextAttemptAt: __t.timestamp().name("next_attempt_at"),
  leaseUntil: __t.option(__t.timestamp()).name("lease_until"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
  expiresAt: __t.timestamp().name("expires_at"),
  suppressedReason: __t.option(__t.string()).name("suppressed_reason"),
  metadataJson: __t.option(__t.string()).name("metadata_json"),
});
