// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  agentId: __t.string().name("agent_id"),
  handle: __t.string(),
  displayName: __t.string().name("display_name"),
  role: __t.string(),
  online: __t.bool(),
  wakeable: __t.bool(),
  availability: __t.string(),
  acceptsNewConversations: __t.bool().name("accepts_new_conversations"),
  expectedWakeLatencyMs: __t.option(__t.u64()).name("expected_wake_latency_ms"),
  wakeLatencyClass: __t.option(__t.string()).name("wake_latency_class"),
  supportedWakeReasonsJson: __t.string().name("supported_wake_reasons_json"),
  statusText: __t.option(__t.string()).name("status_text"),
  updatedAt: __t.timestamp().name("updated_at"),
});
