// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64(),
  taskId: __t.u64().name("task_id"),
  claimantIdentity: __t.identity().name("claimant_identity"),
  status: __t.string(),
  claimedAt: __t.timestamp().name("claimed_at"),
  releasedAt: __t.option(__t.timestamp()).name("released_at"),
});
