// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  attemptId: __t.string().name("attempt_id"),
  wakeId: __t.string().name("wake_id"),
  registrationId: __t.option(__t.string()).name("registration_id"),
  recipientAgentId: __t.string().name("recipient_agent_id"),
  attemptNumber: __t.u64().name("attempt_number"),
  status: __t.string(),
  claimedBy: __t.identity().name("claimed_by"),
  claimedAt: __t.timestamp().name("claimed_at"),
  dispatchedAt: __t.option(__t.timestamp()).name("dispatched_at"),
  completedAt: __t.option(__t.timestamp()).name("completed_at"),
  leaseUntil: __t.timestamp().name("lease_until"),
  error: __t.option(__t.string()),
  metadataJson: __t.option(__t.string()).name("metadata_json"),
});
