// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  key: __t.string(),
  agentId: __t.string().name("agent_id"),
  conversationId: __t.u64().name("conversation_id"),
  role: __t.string(),
  kind: __t.string(),
  title: __t.string(),
  lastActivity: __t.timestamp().name("last_activity"),
  lastSequence: __t.u64().name("last_sequence"),
  lastReadSequence: __t.u64().name("last_read_sequence"),
  unreadCount: __t.u64().name("unread_count"),
  active: __t.bool(),
  joinedAt: __t.timestamp().name("joined_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
