// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  key: __t.string(),
  lastRunAt: __t.timestamp().name("last_run_at"),
  reason: __t.string(),
  deliveryDeleted: __t.u64().name("delivery_deleted"),
  receiptDeleted: __t.u64().name("receipt_deleted"),
  accountDirectoryRequestDeleted: __t.u64().name("account_directory_request_deleted"),
  channelDirectoryRequestDeleted: __t.u64().name("channel_directory_request_deleted"),
  conversationMessageRequestDeleted: __t.u64().name("conversation_message_request_deleted"),
  archiveBatchRequestDeleted: __t.u64().name("archive_batch_request_deleted"),
  rateLimitBucketDeleted: __t.u64().name("rate_limit_bucket_deleted"),
  requestLogDeleted: __t.u64().name("request_log_deleted"),
  agentEventDeleted: __t.u64().name("agent_event_deleted"),
  conversationMessageDeleted: __t.u64().name("conversation_message_deleted"),
  capped: __t.bool(),
});
