// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  key: __t.string(),
  hotMessageRetentionSeconds: __t.u64().name("hot_message_retention_seconds"),
  hotRetentionHours: __t.u64().name("hot_retention_hours"),
  deliveryRetentionSeconds: __t.u64().name("delivery_retention_seconds"),
  clientReceiptRetentionSeconds: __t.u64().name("client_receipt_retention_seconds"),
  archiveRequiredBeforePurge: __t.bool().name("archive_required_before_purge"),
  archiveConfigured: __t.bool().name("archive_configured"),
});
