// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64(),
  channelId: __t.u64().name("channel_id"),
  title: __t.string(),
  description: __t.string(),
  status: __t.string(),
  priority: __t.string(),
  createdBy: __t.identity().name("created_by"),
  assignedTo: __t.option(__t.identity()).name("assigned_to"),
  correlationId: __t.option(__t.string()).name("correlation_id"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
