// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  key: __t.string(),
  capturedAt: __t.timestamp().name("captured_at"),
  activeConnections: __t.u64().name("active_connections"),
  activeConnectionAgents: __t.u64().name("active_connection_agents"),
  activeAccounts: __t.u64().name("active_accounts"),
  activeAgentProfiles: __t.u64().name("active_agent_profiles"),
  conversationCount: __t.u64().name("conversation_count"),
  conversationMemberCount: __t.u64().name("conversation_member_count"),
  conversationDeliveryCount: __t.u64().name("conversation_delivery_count"),
  unreadDeliveryCount: __t.u64().name("unread_delivery_count"),
  agentDeliveryCounterUnreadTotal: __t.u64().name("agent_delivery_counter_unread_total"),
  conversationParticipantIndexCount: __t.u64().name("conversation_participant_index_count"),
  requestRowCount: __t.u64().name("request_row_count"),
  rateLimitBucketCount: __t.u64().name("rate_limit_bucket_count"),
  cleanupCapped: __t.bool().name("cleanup_capped"),
  lastCleanupRunAt: __t.timestamp().name("last_cleanup_run_at"),
  deploymentDisableNewAccounts: __t.bool().name("deployment_disable_new_accounts"),
  deploymentDisableMessageSend: __t.bool().name("deployment_disable_message_send"),
});
