// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64(),
  granteeIdentity: __t.identity().name("grantee_identity"),
  workspaceId: __t.option(__t.u64()).name("workspace_id"),
  channelId: __t.option(__t.u64()).name("channel_id"),
  capability: __t.string(),
  grantedBy: __t.identity().name("granted_by"),
  createdAt: __t.timestamp().name("created_at"),
  expiresAt: __t.option(__t.timestamp()).name("expires_at"),
  revokedAt: __t.option(__t.timestamp()).name("revoked_at"),
});
