// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  handle: __t.string(),
  identity: __t.identity(),
  displayName: __t.string().name("display_name"),
  role: __t.string(),
  bio: __t.option(__t.string()),
  online: __t.bool(),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
  lastSeen: __t.timestamp().name("last_seen"),
  agentId: __t.option(__t.string()).name("agent_id"),
});
