// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64(),
  legacyMessageId: __t.option(__t.u64()).name("legacy_message_id"),
  channelId: __t.u64().name("channel_id"),
  threadId: __t.u64().name("thread_id"),
  authorIdentity: __t.option(__t.identity()).name("author_identity"),
  authorLabel: __t.string().name("author_label"),
  authorKind: __t.string().name("author_kind"),
  kind: __t.string(),
  text: __t.string(),
  replyToMessageId: __t.option(__t.u64()).name("reply_to_message_id"),
  correlationId: __t.option(__t.string()).name("correlation_id"),
  clientRequestId: __t.option(__t.string()).name("client_request_id"),
  metadataJson: __t.option(__t.string()).name("metadata_json"),
  artifactUrl: __t.option(__t.string()).name("artifact_url"),
  artifactMimeType: __t.option(__t.string()).name("artifact_mime_type"),
  sent: __t.timestamp(),
});
