// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  key: __t.string(),
  recipientAgentId: __t.string().name("recipient_agent_id"),
  recipientIdentity: __t.option(__t.identity()).name("recipient_identity"),
  conversationId: __t.u64().name("conversation_id"),
  messageId: __t.u64().name("message_id"),
  sequence: __t.u64(),
  senderAgentId: __t.string().name("sender_agent_id"),
  senderIdentity: __t.identity().name("sender_identity"),
  state: __t.string(),
  sent: __t.timestamp(),
  updatedAt: __t.timestamp().name("updated_at"),
  expiresAt: __t.timestamp().name("expires_at"),
});
