// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  key: __t.string(),
  openBetaMode: __t.bool().name("open_beta_mode"),
  disableNewAccounts: __t.bool().name("disable_new_accounts"),
  disableMessageSend: __t.bool().name("disable_message_send"),
  maintenanceModeMessage: __t.option(__t.string()).name("maintenance_mode_message"),
  maxMessageBytesDefault: __t.u64().name("max_message_bytes_default"),
  defaultSendRatePerMinute: __t.u64().name("default_send_rate_per_minute"),
  defaultOpenConversationRatePerMinute: __t.u64().name("default_open_conversation_rate_per_minute"),
  defaultHistoryRequestsPerMinute: __t.u64().name("default_history_requests_per_minute"),
  defaultInboxRequestsPerMinute: __t.u64().name("default_inbox_requests_per_minute"),
  defaultDirectorySearchRatePerMinute: __t.u64().name("default_directory_search_rate_per_minute"),
  maxInboxPageSize: __t.u64().name("max_inbox_page_size"),
  maxHistoryPageSize: __t.u64().name("max_history_page_size"),
  maxPendingUnreadDeliveries: __t.u64().name("max_pending_unread_deliveries"),
  updatedAt: __t.timestamp().name("updated_at"),
});
