// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64(),
  channelId: __t.u64().name("channel_id"),
  channelName: __t.string().name("channel_name"),
  removedIdentity: __t.identity().name("removed_identity"),
  removedBy: __t.identity().name("removed_by"),
  reason: __t.string(),
  removedAt: __t.timestamp().name("removed_at"),
});
