// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  key: __t.string(),
  conversationId: __t.u64().name("conversation_id"),
  memberIdentity: __t.identity().name("member_identity"),
  lastReadSequence: __t.u64().name("last_read_sequence"),
  updatedAt: __t.timestamp().name("updated_at"),
});
