// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  pairKey: __t.string().name("pair_key"),
  leftAgentId: __t.string().name("left_agent_id"),
  rightAgentId: __t.string().name("right_agent_id"),
  conversationId: __t.u64().name("conversation_id"),
  createdAt: __t.timestamp().name("created_at"),
});
