// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AcceptHandoffReducer from "../accept_handoff_reducer";
import AcceptWorkspaceInviteReducer from "../accept_workspace_invite_reducer";
import AddConversationMemberReducer from "../add_conversation_member_reducer";
import BootstrapOperatorAccountReducer from "../bootstrap_operator_account_reducer";
import ClaimTaskReducer from "../claim_task_reducer";
import ClearAccountDirectoryRequestReducer from "../clear_account_directory_request_reducer";
import ClearChannelDirectoryRequestReducer from "../clear_channel_directory_request_reducer";
import ClearConversationMessageRequestReducer from "../clear_conversation_message_request_reducer";
import CreateAccountReducer from "../create_account_reducer";
import CreateChannelReducer from "../create_channel_reducer";
import CreateDirectConversationReducer from "../create_direct_conversation_reducer";
import CreateGroupConversationReducer from "../create_group_conversation_reducer";
import CreateHandoffReducer from "../create_handoff_reducer";
import CreateTaskReducer from "../create_task_reducer";
import CreateThreadReducer from "../create_thread_reducer";
import CreateWorkspaceReducer from "../create_workspace_reducer";
import CreateWorkspaceChannelReducer from "../create_workspace_channel_reducer";
import CreateWorkspaceInviteReducer from "../create_workspace_invite_reducer";
import EmitAgentEventReducer from "../emit_agent_event_reducer";
import GrantCapabilityReducer from "../grant_capability_reducer";
import JoinChannelReducer from "../join_channel_reducer";
import KickFromRoomReducer from "../kick_from_room_reducer";
import LeaveChannelReducer from "../leave_channel_reducer";
import LeaveConversationReducer from "../leave_conversation_reducer";
import MarkConversationReadReducer from "../mark_conversation_read_reducer";
import RegisterAgentReducer from "../register_agent_reducer";
import RepairAccessStateReducer from "../repair_access_state_reducer";
import RequestAccountDirectoryReducer from "../request_account_directory_reducer";
import RequestChannelDirectoryReducer from "../request_channel_directory_reducer";
import RequestConversationMessagesReducer from "../request_conversation_messages_reducer";
import RevokeCapabilityReducer from "../revoke_capability_reducer";
import SendConversationMessageReducer from "../send_conversation_message_reducer";
import SendThreadMessageReducer from "../send_thread_message_reducer";
import SetAccountTypeReducer from "../set_account_type_reducer";
import SetProfileReducer from "../set_profile_reducer";
import SetRoomConfigReducer from "../set_room_config_reducer";
import SetRoomRoleReducer from "../set_room_role_reducer";
import UnwatchThreadReducer from "../unwatch_thread_reducer";
import UpdateTaskStatusReducer from "../update_task_status_reducer";
import WatchThreadReducer from "../watch_thread_reducer";

export type AcceptHandoffParams = __Infer<typeof AcceptHandoffReducer>;
export type AcceptWorkspaceInviteParams = __Infer<typeof AcceptWorkspaceInviteReducer>;
export type AddConversationMemberParams = __Infer<typeof AddConversationMemberReducer>;
export type BootstrapOperatorAccountParams = __Infer<typeof BootstrapOperatorAccountReducer>;
export type ClaimTaskParams = __Infer<typeof ClaimTaskReducer>;
export type ClearAccountDirectoryRequestParams = __Infer<typeof ClearAccountDirectoryRequestReducer>;
export type ClearChannelDirectoryRequestParams = __Infer<typeof ClearChannelDirectoryRequestReducer>;
export type ClearConversationMessageRequestParams = __Infer<typeof ClearConversationMessageRequestReducer>;
export type CreateAccountParams = __Infer<typeof CreateAccountReducer>;
export type CreateChannelParams = __Infer<typeof CreateChannelReducer>;
export type CreateDirectConversationParams = __Infer<typeof CreateDirectConversationReducer>;
export type CreateGroupConversationParams = __Infer<typeof CreateGroupConversationReducer>;
export type CreateHandoffParams = __Infer<typeof CreateHandoffReducer>;
export type CreateTaskParams = __Infer<typeof CreateTaskReducer>;
export type CreateThreadParams = __Infer<typeof CreateThreadReducer>;
export type CreateWorkspaceParams = __Infer<typeof CreateWorkspaceReducer>;
export type CreateWorkspaceChannelParams = __Infer<typeof CreateWorkspaceChannelReducer>;
export type CreateWorkspaceInviteParams = __Infer<typeof CreateWorkspaceInviteReducer>;
export type EmitAgentEventParams = __Infer<typeof EmitAgentEventReducer>;
export type GrantCapabilityParams = __Infer<typeof GrantCapabilityReducer>;
export type JoinChannelParams = __Infer<typeof JoinChannelReducer>;
export type KickFromRoomParams = __Infer<typeof KickFromRoomReducer>;
export type LeaveChannelParams = __Infer<typeof LeaveChannelReducer>;
export type LeaveConversationParams = __Infer<typeof LeaveConversationReducer>;
export type MarkConversationReadParams = __Infer<typeof MarkConversationReadReducer>;
export type RegisterAgentParams = __Infer<typeof RegisterAgentReducer>;
export type RepairAccessStateParams = __Infer<typeof RepairAccessStateReducer>;
export type RequestAccountDirectoryParams = __Infer<typeof RequestAccountDirectoryReducer>;
export type RequestChannelDirectoryParams = __Infer<typeof RequestChannelDirectoryReducer>;
export type RequestConversationMessagesParams = __Infer<typeof RequestConversationMessagesReducer>;
export type RevokeCapabilityParams = __Infer<typeof RevokeCapabilityReducer>;
export type SendConversationMessageParams = __Infer<typeof SendConversationMessageReducer>;
export type SendThreadMessageParams = __Infer<typeof SendThreadMessageReducer>;
export type SetAccountTypeParams = __Infer<typeof SetAccountTypeReducer>;
export type SetProfileParams = __Infer<typeof SetProfileReducer>;
export type SetRoomConfigParams = __Infer<typeof SetRoomConfigReducer>;
export type SetRoomRoleParams = __Infer<typeof SetRoomRoleReducer>;
export type UnwatchThreadParams = __Infer<typeof UnwatchThreadReducer>;
export type UpdateTaskStatusParams = __Infer<typeof UpdateTaskStatusReducer>;
export type WatchThreadParams = __Infer<typeof WatchThreadReducer>;

