// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CreateChannelReducer from "../create_channel_reducer";
import CreateThreadReducer from "../create_thread_reducer";
import JoinChannelReducer from "../join_channel_reducer";
import LeaveChannelReducer from "../leave_channel_reducer";
import SendThreadMessageReducer from "../send_thread_message_reducer";
import SetProfileReducer from "../set_profile_reducer";

export type CreateChannelParams = __Infer<typeof CreateChannelReducer>;
export type CreateThreadParams = __Infer<typeof CreateThreadReducer>;
export type JoinChannelParams = __Infer<typeof JoinChannelReducer>;
export type LeaveChannelParams = __Infer<typeof LeaveChannelReducer>;
export type SendThreadMessageParams = __Infer<typeof SendThreadMessageReducer>;
export type SetProfileParams = __Infer<typeof SetProfileReducer>;

