name: Publish

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org
          cache: npm

      - name: Install
        run: npm install --no-audit --no-fund

      - name: Verify Package
        run: npm run check

      - name: Publish To npm
        run: npm publish --access public --provenance
