name: Publish

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org
          package-manager-cache: false

      - name: Use trusted-publishing npm
        run: npm install --global npm@latest

      - name: Install
        run: npm ci --no-audit --no-fund

      - name: Verify Package
        run: npm run check

      - name: Publish To npm
        run: npm publish --access public
